---
sudo: required

env:
  - distribution: "centos"
    version: "7"
  - distribution: "ubuntu"
    version: "bionic"
  - distribution: "ubuntu"
    version: "xenial"
  - distribution: "ubuntu"
    version: "trusty"
  - distribution: "debian"
    version: "stretch"
  - distribution: "debian"
    version: "jessie"

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests/travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/proactcloud.openssh:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker cp travis/openssh_hostkey.py "$(cat ${container_id}):/etc/ansible/modules/openssh_hostkey.py"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install willshersystems.sshd'
  - 'sudo docker exec "$(cat ${container_id})" mkdir /run/sshd'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ANSIBLE_LIBRARY=/etc/ansible/modules ansible-playbook -v /etc/ansible/roles/proactcloud.openssh/tests/travis/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ANSIBLE_LIBRARY=/etc/ansible/modules ansible-playbook -v /etc/ansible/roles/proactcloud.openssh/tests/travis/test.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ANSIBLE_LIBRARY=/etc/ansible/modules ansible-playbook -v /etc/ansible/roles/proactcloud.openssh/tests/travis/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'
