---
- name: Ensure SSH allow group exists.
  group:
    name: "{{ pacopenssh_allow_group }}"
    state: present
    system: true

- name: Get SSH username
  become: no
  set_fact:
    pac_sshuser: "{{ lookup('env', 'USER' }}"

- name: Ensure users are in SSH allow group
  user:
    name: "{{ item }}"
    groups: "{{ pacopenssh_allow_group }}"
    append: yes
  loop: "{{ pacopenssh_allow_group_users }}"

- name: Add current ansible user and root to SSH allow group (safety pin)
  user:
    name: "{{ item }}"
    groups: "{{ pacopenssh_allow_group }}"
    append: yes
  loop:
    - root
    - "{{ pac_sshuser }}"
  when: pacopenssh_safety_pin | bool

- name: Setup SSHd config (willshersystems.sshd role)
  include_role:
    name: willshersystems.sshd
  vars:
    sshd: "{{ pacopenssh_sshd }}"

- name: Disable ECDSA key generation in rc.d/ssh
  lineinfile:
    dest: /etc/rc.conf
    insertbefore: EOF
    line: sshd_ecdsa_enable="no"
    state: present
  when: ansible_system == "FreeBSD"

# Check and replace hostkeys, if needed.
# This will also update the local known_host file automagically ;-)
# Goal: No RSA1 (Protocol Version 1) Key, No DSA key, RSA key of 4096 bits,
#       no ECDSA key and an ED25519 key (128 Bits, not changeable)
- name: Harden SSHd | remove RSA1 hostkey.
  openssh_hostkey:
    type: RSA1
    state: absent
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]

- name: Harden SSHd | remove DSA hostkey.
  openssh_hostkey:
    type: DSA
    state: absent
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]

- name: Harden SSHd | Enforce 4096 bits RSA hostkey.
  openssh_hostkey:
    type: RSA
    size: 4096
    state: present
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]

- name: Harden SSHd | Remove 521 bits ECDSA key.
  openssh_hostkey:
    type: ECDSA
    state: absent
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Harden SSHd | Enforce 521 bits ECDSA key.
  openssh_hostkey:
    type: ECDSA
    size: 521
    state: present
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Harden SSHd | Enforce existence of ED25519 hostkey.
  openssh_hostkey:
    type: ED25519
    size: 128
    state: present
    path: "{{ pacopenssh_conf_dir }}"
  notify: [ 'restart_sshd' ]

- name: Harden SSHd | Deploy large RSA moduli.
  copy:
    dest: "{{ pacopenssh_conf_dir }}/moduli"
    group: "{{ root_group }}"
    mode: 0644
    owner: root
    src: moduli.safe

# Install a ssh_config with similar defaults to the SSHd config. Can always be overridden by user.
- name: Harden SSH | Install ssh_config.
  template:
    group: "{{ root_group }}"
    mode: 0644
    owner: root
    dest: "{{ pacopenssh_conf_dir }}/ssh_config"
    src: ssh_config.j2
