---
- name: Install python-cryptography from packages (not on Debian8 / Ubuntu 16.04 / Ubuntu 14.04)
  package:
    name: "{{ pacopenssh_pycrypto_package }}"
    state: present
  when: not ((ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"))

- name: Install required packages required for build of python-cryptography (Debian8 / Ubuntu 16.04 / Ubuntu 14.04)
  package:
    name: "{{ item }}"
    state: present
  when: ((ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"))
  with_items:
    - python-setuptools
    - build-essential
    - libssl-dev
    - python-dev

- name: Install additional build dependency for python-cryptography (Ubuntu 14.04)
  package:
    name: libffi-dev
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")

- name: Install python-pip (Ubuntu 16.04 / Ubuntu 14.04 / Debian 8)
  package:
    name: python-pip
    state: present
  when: ((ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04")  or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"))
  register: pkg_pip
  changed_when: pkg_pip.changed and ((ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04")  or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"))

- name: Update pip from pip using packaged pip (Debian 8)
  pip:
    name: pip
    state: latest
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: Remove packaged pip to use updated pip (Debian 8)
  package:
    name: python-pip
    state: absent
  changed_when: false
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: Install latest (python-)cryptography from pip (Debian8 / Ubuntu 16.04)
  pip:
    name: cryptography
    state: latest
  when: ((ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"))

- name: Install (python-)cryptography 2.0.3 from pip (Ubuntu 14.04)
  pip:
    name: cryptography
    version: 2.0.3
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")
