---
- name: Install python-cryptography from packages (not on Debian8 / Ubuntu 16.04)
  package:
    name: "{{ pacopenssh_pycrypto_package }}"
    state: present
  when: not (( ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"))

- name: Install required packages required for build of python-cryptography (Debian8 / Ubuntu 16.04)
  package:
    name: "{{ item }}"
    state: present
  when: (( ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"))
  with_items:
    - python-setuptools
    - build-essential
    - libssl-dev
    - python-dev

- name: Install PIP (easy_install) (Debian8)
  command: /usr/bin/easy_install pip
  args:
    creates: /usr/local/bin/pip
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: Install python-pip (Ubuntu 16.04)
  package:
    name: python-pip
    state: present
  when: (( ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"))

- name: Install latest (python-)cryptography from pip (Debian8 / Ubuntu 16.04)
  pip:
    name: cryptography
    state: present
  when: (( ansible_distribution == "Debian" and ansible_distribution_major_version == "8") or ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"))
