---
# tasks file for teamix.openssh
###
# SSH Configuration - Hardening of Server
# Configuration based on https://stribika.github.io/2015/01/04/secure-secure-shell.html
###

- name: Include Distro dependent vars
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Include Installation procedures
  include: install.yml
  tags: [ install ]

- name: Include Configuration procedures
  include: config.yml
  tags: [ config ]
