---
# tasks file for proactcloud.openssh
###
# SSH Configuration - Hardening of Server
# Configuration based on https://stribika.github.io/2015/01/04/secure-secure-shell.html
###

- name: Include Distro dependent vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - distro_default.yml
      paths:
        - 'vars'

- name: Include Installation procedures
  include: install.yml
  tags: [ install ]

- name: Include Configuration procedures
  include: config.yml
  tags: [ config ]
